# Generated by Django 5.2.6 on 2025-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
